name = "remote-assets-proxy"
main = "src/index.js" 
compatibility_date = "2025-03-23"

[vars]
ASSETS_R2_DOMAIN = "https://assets.daolanx.com"
ASSETS_PREFIX = "/remote-assets/"
UPLOADS_R2_DOMAIN = "https://files.daolanx.com"
UPLOADS_PREFIX = "/medias/"

[[routes]]
pattern = "demo.daolanx.com/remote-assets/*"
zone_name = "daolanx.com"

[[routes]]
pattern = "demo.daolanx.com/medias/*"
zone_name = "daolanx.com"

[[r2_buckets]]
binding = "R2_BUCKET"
bucket_name = "assets" 