name = "remote-assets-proxy"
main = "src/index.js" 
compatibility_date = "2025-03-23"

[vars]
R2_DOMAIN = "https://assets.daolanx.com"
REMOTE_PREFIX = "/remote-assets/"

[[routes]]
pattern = "demo.daolanx.com/remote-assets/*"
zone_name = "daolanx.com"