import type { Metadata } from 'next';
import './globals.css';
import { Outfit } from 'next/font/google';
import { cn } from '@/lib/utils';

const gilroy = Outfit({ subsets: ['latin'], variable: '--font-gilroy' });

export const metadata: Metadata = {
  title: 'Demo App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={cn('font-gilroy', gilroy.variable)}>
      <body>{children}</body>
    </html>
  );
}
